version: '3'

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  web:
    image: nginx:1.16-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    networks:
      - backend
  app:
    build: ./docker/php
    volumes:
      - ./:/var/www/
    networks:
      - backend
  mysql:
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=app_default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - backend